### ISSUE TITLE
Empty .graphml file for Baboons Franz Grooming 24 

### ISSUE THREAD

**Issue by eloisenewman** [bansallab/asnr#6]
Hi,

Great repository! I have been having a play with the baboons graphs and have noticed that for "baboon_franz_grooming_group_24.graphml" it is an empty network. I was wondering if it is meant to be empty? 

Cheers,

Eloise

**Comment by mac532** [comment]
Hi Eloise! Thanks for catching this. I went back and checked the original data source for this network and the associated adjacency matrix is indeed all zeros (and empty network). I am going to go ahead and remove this one from the repository since I'm not positive whether this is an error with the original source data, or if is meant to be this way. Please reach out if you have any other questions!

-Melissa
